language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

env:
  matrix:
    - DEPENDENCIES=""
    - DEPENDENCIES="--prefer-lowest --prefer-stable"

before_script:
  - composer self-update
  - composer update --prefer-dist $DEPENDENCIES

script:
  - composer test
  - composer cs
  - composer md
